# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bc8cd3264236e0ad65a65febbdd50e48eed2103c43b6ec41d220655cbec2e52c93d928b2c14a8b97f1cfca1b08d0b669fe19f8db7d93c91a5029d93177922ee

test:
  secret_key_base: bbc90aa53d213cf8cb0d36ba4a2444118e6d6eb21ef97362f0349c7f45d0645caac0f817f7027e1297ce58fcb314c96e7441aeae3628724e81aa24504cac1ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
